title: Just a Blog
email: eduardo.acye@gmail.com
description: >- #
  This is just a blog.
baseurl: ""
url: ""
github_username: eduardoacye

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
color_scheme: github
mathjax: true
