title: Solo un blog
email: eduardo.acye@gmail.com
description: >- #
  Este es solo un blog.
baseurl: ""
url: ""
github_username: eduardoacye

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
color_scheme: github
mathjax: true
plugins:
  - jekyll-seo-tag
